Add Vanta AWS account ID
fwdcloudsec/known_aws_accounts pull request #20
Opened 2023-09-08 13:09 UTC by christophetd

2023-09-12 20:46 UTC, 0xdabbad00 commented on accounts.yaml
> +  source: 'https://github.com/rupertbg/aws-public-account-ids/blob/master/accounts.json#L500C10-L500C22'
I want to try to use references from the vendors. For whatever reason Wiz does not make their account IDs public.

2023-09-12 20:48 UTC, christophetd commented on accounts.yaml
> +  source: 'https://github.com/rupertbg/aws-public-account-ids/blob/master/accounts.json#L500C10-L500C22'
How about we link to the (private) Wiz docs? At least it's the vendor reference, even if only customers can access it (it's effectively public anyway)

2023-09-25 08:43 UTC, new23d requested changes

2023-09-25 08:43 UTC, new23d commented on accounts.yaml
> +  source: 'https://console.prosperops.com/onboarding'
requires login, so couldn't verify

2023-09-25 08:43 UTC, new23d commented on accounts.yaml
> +  source: 'https://docs.nops.io/en/articles/6818153-aws-setup-permissions-sharesave-auto-pilot-risk-free-commitment-management'
i'm getting a 404 on this link, so couldn't verify

2023-09-25 08:43 UTC, new23d commented on accounts.yaml
> +  source: 'https://cloudopt.usage.ai/onboard'
requires login, so couldn't verify

2023-09-25 08:43 UTC, new23d commented on accounts.yaml
> +  source: 'https://ubuntu.com/blog/time-to-prepare-for-ubuntu-18-04-lts-end-of-standard-support-on-31-may-2023-options-for-aws-users#:~:text=EC2%20describe%2Dimages%3A-,aws%20ec2%20describe%2Dimages,
`https://ubuntu.com/server/docs/cloud-images/amazon-ec2` is a simpler, more authoritative source

2023-09-25 09:19 UTC, christophetd commented on accounts.yaml
> +  source: 'https://docs.nops.io/en/articles/6818153-aws-setup-permissions-sharesave-auto-pilot-risk-free-commitment-management'
indeed, looks like they changed the URL. The article still shows up if you search for the account ID on Google

![image](https://github.com/fwdcloudsec/known_aws_accounts/assets/136675/49c09978-75bf-4b36-b652-17cd38c153e0)

Will update to their new docs https://help.nops.io/iam-yaml-sharesave.html#sharesave-yaml-file

2023-09-25 09:19 UTC, christophetd commented on accounts.yaml
> +  source: 'https://docs.nops.io/en/articles/6818153-aws-setup-permissions-sharesave-auto-pilot-risk-free-commitment-management'
```suggestion
  source: 'https://help.nops.io/iam-yaml-sharesave.html#sharesave-yaml-file'
```

2023-09-25 09:20 UTC, christophetd commented on accounts.yaml
> +  source: 'https://ubuntu.com/blog/time-to-prepare-for-ubuntu-18-04-lts-end-of-standard-support-on-31-may-2023-options-for-aws-users#:~:text=EC2%20describe%2Dimages%3A-,aws%20ec2%20describe%2Dimages,
```suggestion
  source: 'https://ubuntu.com/server/docs/cloud-images/amazon-ec2'
```

2023-09-25 09:49 UTC, new23d approved these changes

2023-09-25 09:49 UTC, new23d commented on accounts.yaml
> +  source: 'https://console.prosperops.com/onboarding'
screenshot confirms the account id

2023-09-25 09:49 UTC, new23d commented on accounts.yaml
> +  source: 'https://cloudopt.usage.ai/onboard'
screenshot confirms the account id

2023-09-25 09:53 UTC, new23d commented
I have verified all the sources. This PR is good to merge.

2023-09-26 01:58 UTC, merged